///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//package domain.ui;
//
///**
// *
// * @author bozhi
// */
//public class HomeFrame extends javax.swing.JFrame {
//
//    /**
//     * Creates new form homeFrame
//     */
//    public HomeFrame() {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jPopupMenu1 = new javax.swing.JPopupMenu();
//        jMenuBar1 = new javax.swing.JMenuBar();
//        jMenu2 = new javax.swing.JMenu();
//        jMenu1 = new javax.swing.JMenu();
//        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
//        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
//        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
//        jMenu3 = new javax.swing.JMenu();
//        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
//        jPanel1 = new javax.swing.JPanel();
//        jLabel1 = new javax.swing.JLabel();
//        jToolBar1 = new javax.swing.JToolBar();
//        jButton1 = new javax.swing.JButton();
//        jLabel2 = new javax.swing.JLabel();
//
//        jMenu2.setText("File");
//
//        jMenu1.setText("jMenu1");
//
//        jCheckBoxMenuItem2.setSelected(true);
//        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");
//        jMenu1.add(jCheckBoxMenuItem2);
//
//        jRadioButtonMenuItem2.setSelected(true);
//        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");
//        jMenu1.add(jRadioButtonMenuItem2);
//
//        jMenu2.add(jMenu1);
//
//        jRadioButtonMenuItem1.setSelected(true);
//        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");
//        jMenu2.add(jRadioButtonMenuItem1);
//
//        jMenuBar1.add(jMenu2);
//
//        jMenu3.setText("Edit");
//
//        jCheckBoxMenuItem1.setSelected(true);
//        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");
//        jMenu3.add(jCheckBoxMenuItem1);
//
//        jMenuBar1.add(jMenu3);
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
//
//        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
//        jLabel1.setText("Lab Inventory System");
//
//        jToolBar1.setRollover(true);
//
//        jButton1.setFont(new java.awt.Font("�s�ө���", 1, 15)); // NOI18N
//        jButton1.setText("Inventory");
//        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
//        jButton1.setFocusable(false);
//        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
//        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        jButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton1ActionPerformed(evt);
//            }
//        });
//        jToolBar1.add(jButton1);
//
//        jLabel2.setFont(new java.awt.Font("�з���", 1, 24)); // NOI18N
//        jLabel2.setText("Welcome to Lab 1321");
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(jPanel1Layout.createSequentialGroup()
//                        .addGap(89, 89, 89)
//                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
//                    .addGroup(jPanel1Layout.createSequentialGroup()
//                        .addGap(140, 140, 140)
//                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                            .addComponent(jLabel2)
//                            .addComponent(jLabel1))))
//                .addContainerGap(132, Short.MAX_VALUE))
//        );
//        jPanel1Layout.setVerticalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(jLabel1)
//                .addGap(18, 18, 18)
//                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(88, 88, 88)
//                .addComponent(jLabel2)
//                .addContainerGap(81, Short.MAX_VALUE))
//        );
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        // TODO add your handling code here:
//        dispose();
//        new InventoryFrame().setVisible(true);
//    }//GEN-LAST:event_jButton1ActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomeFrame().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JButton jButton1;
//    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
//    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JMenu jMenu1;
//    private javax.swing.JMenu jMenu2;
//    private javax.swing.JMenu jMenu3;
//    private javax.swing.JMenuBar jMenuBar1;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JPopupMenu jPopupMenu1;
//    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
//    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
//    private javax.swing.JToolBar jToolBar1;
//    // End of variables declaration//GEN-END:variables
//}
