/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domain.ui;

import domain.controller.Controller;
import domain.controller.IController;
import domain.labMember.*;

/**
 *
 * @author bozhi
 */
public class MainFrame extends javax.swing.JFrame {
    private HomePanel homePanel;
    private InventoryPanel inventoryPanel;
    private LoginPanel loginPanel;
    private IController controller;
    private SettingPanel settingPanel;
    private NotificationPanel notificationPanel;
    private ILabMemberList labMemberList;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        controller = new Controller();
//        labMemberList = new LabMemberList();
        labMemberList = new LabMemberListInDB();
        dbInit(controller, labMemberList);
//        init(controller, labMemberList);
        loginPanel.setVisible(true);
        initComponents();
    }
    
    public LoginPanel getLoginPanel() {
        return loginPanel;
    }
    
    public HomePanel getHomePanel() {
        return homePanel;
    }
    
    public InventoryPanel getInventoryPanel() {
        return inventoryPanel;
    }
    
    public SettingPanel getSettingPanel() {
        return settingPanel;
    }
        
    public NotificationPanel getNotificationPanel() {
        return notificationPanel;
    }

    private void dbInit(IController controller, ILabMemberList labMemberList) {
        homePanel = new HomePanel(this, controller);
        inventoryPanel = new InventoryPanel(this, controller, labMemberList);
        loginPanel = new LoginPanel(this, controller, labMemberList);
        settingPanel = new SettingPanel(this, controller);
        notificationPanel = new NotificationPanel(this, controller);

        this.add(loginPanel);
        this.add(homePanel);
        this.add(inventoryPanel);
        this.add(settingPanel);
        this.add(notificationPanel);
    }
    
    private void init(IController controller, ILabMemberList labMemberList) {
        Admin admin = new Admin("Admin", "admin@gmail.com", "admin");
        admin.setPhone("0909123456");
        Manager manager = new Manager("Manager", "manager@gmail.com", "manager");
        manager.setPhone("0909123456");
        labMemberList.addLabMember(admin);
        labMemberList.addLabMember(manager);
        
        homePanel = new HomePanel(this, controller);
        inventoryPanel = new InventoryPanel(this, controller, labMemberList);
        loginPanel = new LoginPanel(this, controller, labMemberList);
        settingPanel = new SettingPanel(this, controller);
        notificationPanel = new NotificationPanel(this, controller);
        
        this.add(loginPanel);
        this.add(homePanel);
        this.add(inventoryPanel);
        this.add(settingPanel);
        this.add(notificationPanel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lab Inventory System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
