/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domain.ui;

import java.awt.GridLayout;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class PopMenu extends javax.swing.JPanel {
    
    private String sName;
    private String sAmount;
    private String sLevel;
    
    /**
     * Creates new form PopMenu
     */
    public PopMenu() {
        display();
    }

    private void display() {
        String[] level = {"Important", "Normal"};
        JComboBox<String> combo = new JComboBox<>(level);
        JTextField name = new JTextField("");
        JTextField amount = new JTextField("");
        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(combo);
        panel.add(new JLabel("Input Name: "));
        panel.add(name);
        panel.add(new JLabel("Input Amount: "));
        panel.add(amount);
        int result = JOptionPane.showConfirmDialog(null, panel, "Inventory Detail",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            if( !name.getText().replace(" ", "").isEmpty() ) sName = name.getText();
            else sName = "NaN";
            if ( !amount.getText().replace(" ", "").isEmpty() && amount.getText().matches("[0-9+]") ) sAmount = amount.getText();
            else sAmount = "0";
            sLevel = combo.getSelectedItem().toString();
        } else {
            
        }
    }
    
    public String getLevel(){
        return sLevel;
    }
    
    public String getIName(){
        return this.sName;
    }
    
    public int getIAmount(){
        return Integer.valueOf(this.sAmount);
    }
    
    public void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                display();
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
