/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domain.ui;

import domain.controller.Controller;
import domain.labMember.LabMember;
import java.awt.Dialog.ModalityType;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author lab1321
 */
public class SettingPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private Controller controller;
    private ImageIcon icon;
    private LabMember labMember;
    
    public SettingPanel(MainFrame mainFrame, Controller controller) {
        this.mainFrame = mainFrame;
        this.controller = controller;
        this.setBounds(0, 0, 800, 600);
        initComponents();
        this.setVisible(false);
    }
    
    public void setLabMember(LabMember labMember) {
        this.labMember = labMember;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updatePasswordDialog = new javax.swing.JDialog();
        oldPasswordLabel = new javax.swing.JLabel();
        confirmPasswordLabel = new javax.swing.JLabel();
        newPasswordLabel = new javax.swing.JLabel();
        oldPasswordField = new javax.swing.JPasswordField();
        newPasswordField = new javax.swing.JPasswordField();
        dialogUpdatePasswordBtn = new javax.swing.JButton();
        confirmPasswordField = new javax.swing.JPasswordField();
        dialogTitleLabel = new javax.swing.JLabel();
        goToInventoryBtn = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        goBackHomeBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        updatePasswordBtn = new javax.swing.JButton();
        permissionLabel = new javax.swing.JLabel();
        permissionField = new javax.swing.JTextField();

        updatePasswordDialog.setBackground(new java.awt.Color(204, 204, 204));

        oldPasswordLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        oldPasswordLabel.setText("Old Password:");

        confirmPasswordLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        confirmPasswordLabel.setText("Confrim New Password:");

        newPasswordLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        newPasswordLabel.setText("New Password:");

        oldPasswordField.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        oldPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPasswordFieldActionPerformed(evt);
            }
        });

        newPasswordField.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        newPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordFieldActionPerformed(evt);
            }
        });

        dialogUpdatePasswordBtn.setFont(new java.awt.Font("Lucida Grande", 0, 22)); // NOI18N
        dialogUpdatePasswordBtn.setText("Update Password");
        dialogUpdatePasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogUpdatePasswordBtnActionPerformed(evt);
            }
        });

        confirmPasswordField.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        confirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordFieldActionPerformed(evt);
            }
        });

        dialogTitleLabel.setFont(new java.awt.Font("標楷體", 1, 36)); // NOI18N
        dialogTitleLabel.setText("Update Password");

        javax.swing.GroupLayout updatePasswordDialogLayout = new javax.swing.GroupLayout(updatePasswordDialog.getContentPane());
        updatePasswordDialog.getContentPane().setLayout(updatePasswordDialogLayout);
        updatePasswordDialogLayout.setHorizontalGroup(
            updatePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePasswordDialogLayout.createSequentialGroup()
                .addGroup(updatePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatePasswordDialogLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(dialogTitleLabel))
                    .addGroup(updatePasswordDialogLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(updatePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oldPasswordLabel)
                            .addComponent(newPasswordLabel)
                            .addComponent(confirmPasswordLabel))
                        .addGap(1, 1, 1)
                        .addGroup(updatePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oldPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dialogUpdatePasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        updatePasswordDialogLayout.setVerticalGroup(
            updatePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePasswordDialogLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(dialogTitleLabel)
                .addGap(45, 45, 45)
                .addGroup(updatePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPasswordLabel)
                    .addComponent(oldPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(updatePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newPasswordLabel)
                    .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(updatePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPasswordLabel)
                    .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(dialogUpdatePasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        setBackground(new java.awt.Color(255, 255, 255));

        goToInventoryBtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        goToInventoryBtn.setText("Go To Inventory");
        goToInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToInventoryBtnActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 40)); // NOI18N
        titleLabel.setText("Lab Inventory System");

        goBackHomeBtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        goBackHomeBtn.setText("Go Back Home");
        goBackHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackHomeBtnActionPerformed(evt);
            }
        });

        logoutBtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        nameLabel.setText("Name:");

        nameField.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        nameField.setText("Name");

        emailLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        emailLabel.setText("Email:");

        phoneLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        phoneLabel.setText("Phone:");

        emailField.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        emailField.setText("Email");

        phoneField.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        phoneField.setText("Phone");

        updateBtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        updateBtn.setText("Update User Info");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        updatePasswordBtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        updatePasswordBtn.setText("Update Password");
        updatePasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePasswordBtnActionPerformed(evt);
            }
        });

        permissionLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        permissionLabel.setText("Permission:");

        permissionField.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        permissionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permissionFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(goBackHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(goToInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(permissionLabel)
                                .addGap(18, 18, 18)
                                .addComponent(permissionField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel)
                                    .addComponent(emailLabel)
                                    .addComponent(phoneLabel))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameField)
                                    .addComponent(emailField)
                                    .addComponent(phoneField, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))))
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updatePasswordBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(titleLabel)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goToInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goBackHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneLabel)
                            .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(permissionLabel)
                            .addComponent(permissionField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(updatePasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goToInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToInventoryBtnActionPerformed
        // TODO add your handling code here:
        mainFrame.getContentPane().remove(mainFrame.getSettingPanel());
        mainFrame.getContentPane().add(mainFrame.getInventoryPanel());
        mainFrame.getInventoryPanel().setVisible(true);
        mainFrame.revalidate();
        mainFrame.repaint();
    }//GEN-LAST:event_goToInventoryBtnActionPerformed

    private void goBackHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackHomeBtnActionPerformed
        // TODO add your handling code here:
        mainFrame.getContentPane().remove(mainFrame.getSettingPanel());
        mainFrame.getContentPane().add(mainFrame.getHomePanel());
        mainFrame.getHomePanel().setVisible(true);
        mainFrame.revalidate();
        mainFrame.repaint();
    }//GEN-LAST:event_goBackHomeBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        mainFrame.getContentPane().remove(mainFrame.getSettingPanel());
        mainFrame.getContentPane().add(mainFrame.getLoginPanel());
        mainFrame.getLoginPanel().setVisible(true);
        mainFrame.revalidate();
        mainFrame.repaint();
        mainFrame.getLoginPanel().labMember = null;
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if(!nameField.getText().equals(labMember.getName())){
            labMember.setName(nameField.getText());
            mainFrame.getHomePanel().defaultLabel.setText("Hello, " + labMember.getName());
        }
        if(!emailField.getText().equals(labMember.getEmail()))
            labMember.setEmail(emailField.getText());
        if(!phoneField.getText().equals(labMember.getPhone()))
            labMember.setPhone(phoneField.getText());
    }//GEN-LAST:event_updateBtnActionPerformed

    private void oldPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldPasswordFieldActionPerformed

    private void updatePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePasswordBtnActionPerformed
        // TODO add your handling code here:
        updatePasswordDialog.setBounds(0, 0, 550, 420);
        updatePasswordDialog.setVisible(true);
    }//GEN-LAST:event_updatePasswordBtnActionPerformed

    private void newPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPasswordFieldActionPerformed

    private void confirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordFieldActionPerformed

    private void dialogUpdatePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogUpdatePasswordBtnActionPerformed
        // TODO add your handling code here:
        
        if(String.valueOf(newPasswordField.getPassword()).equals(String.valueOf(confirmPasswordField.getPassword())) 
                && !String.valueOf(newPasswordField.getPassword()).equals(String.valueOf(oldPasswordField.getPassword()))){
            labMember.setPassword(String.valueOf(newPasswordField.getPassword()));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("images/icons8-thumbs-up-64.png"));
            JOptionPane.showMessageDialog(null, "Update Password Sucessfully.", "Update ",JOptionPane.INFORMATION_MESSAGE, icon);
            
            oldPasswordField.setText("");
            newPasswordField.setText("");
            confirmPasswordField.setText("");
            updatePasswordDialog.setVisible(false);
        }
    }//GEN-LAST:event_dialogUpdatePasswordBtnActionPerformed

    private void permissionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permissionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_permissionFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JLabel dialogTitleLabel;
    private javax.swing.JButton dialogUpdatePasswordBtn;
    protected javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton goBackHomeBtn;
    private javax.swing.JButton goToInventoryBtn;
    private javax.swing.JButton logoutBtn;
    protected javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JPasswordField oldPasswordField;
    private javax.swing.JLabel oldPasswordLabel;
    protected javax.swing.JTextField permissionField;
    private javax.swing.JLabel permissionLabel;
    protected javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updatePasswordBtn;
    private javax.swing.JDialog updatePasswordDialog;
    // End of variables declaration//GEN-END:variables

}
